"""Adopt independently verified native knee extension, with preparation phase metadata."""
import json,pathlib,copy,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[4];OUT=pathlib.Path(__file__).parent
load=lambda p:json.loads((ROOT/p).read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
enc=lambda v:(json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode()
vhash=lambda v:sha(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def save(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(enc(v));return str(p.relative_to(ROOT))
b=load('atlas-data/motion/motion-learning.json');reg=load('atlas-data/motion/authoring/registry.json');scenes=load('atlas-data/motion/motion-scenes.json');pol=load('atlas-data/motion/motion-asset-sources.json');accept=load('atlas-data/motion/t66-priority-action-acceptance.json')
for outcome in load(str((OUT/'knee-action-outcome.json').relative_to(ROOT))):
 assert outcome['passed'] and outcome['actionDirection']=='reverse'
 side=outcome['side'];key=outcome['sourceKey'];ident='T66-PRIORITY-'+side[0].upper()+'-RECTUS-KNEE';dest=OUT/('knee-extension-'+side);geometry=load(str((dest/'geometry-record.json').relative_to(ROOT)));p=load(str((dest/'input.json').relative_to(ROOT)));fid=p['family']['id']
 assert not any(a['id']==ident+'-ACTION' for a in b['muscleActions'])
 template=next(a for a in b['motionAssets'] if a.get('sourceBinding',{}).get('subjectSourceKey')==key and a.get('sourceBinding',{}).get('sourceFamilyId')=='knee-flexion-'+side)
 asset=copy.deepcopy(template);definition=copy.deepcopy(next(d for d in b['motionDefinitions'] if d['id']==template['motionDefinitionId']));scene=copy.deepcopy(next(s for s in scenes['sceneManifests'] if s['id']==template['staticBinding']['sceneId']))
 uri=f'atlas-data/assets/motion/{ident.lower()}/motion.glb';refuri=f'atlas-data/assets/derived-glb/{ident.lower()}/reference.glb'
 for path,filename in [(uri,'motion.glb'),(refuri,'reference.glb')]:q=ROOT/path;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes((dest/filename).read_bytes())
 pose={'referencePoseId':p['family']['referencePoseId'],'endPoseId':ident+'-BENT','axis':p['family']['axis'],'pivotMetres':p['family']['pivotMetres'],'endDegrees':p['family']['endDegrees'],'actionDirection':'reverse','meaning':'authored preparation bend then active extension to source rest; not measured normal ROM'}
 explanation='대퇴직근이 무릎을 펴는 작용을 봅니다. 먼저 무릎을 굽혀 준비한 뒤 아래다리와 발을 펴며 처음 자세로 돌아옵니다. 대퇴사두근 4개와 무릎뼈, 아래다리·발의 뼈와 근육을 함께 표시합니다.'
 posture='고관절은 유지하고, 준비 구간의 무릎 굽힘과 대퇴직근의 무릎 폄 구간을 구분합니다.'
 context='주변 근육 표면은 관절 운동에 맞춰 변형되거나 함께 이동합니다. 개별 근육의 활성도·힘·수축 비중을 계산하지 않습니다.'
 claims=[{'id':ident+'-'+field,'field':field,'appliesTo':scope,'contextId':cid,'value':value} for field,scope,cid,value in [('action','action_explanation',None,explanation),('model_posture','posture_condition',None,posture),('model_context','context_role',ident+'-CONTEXT',context)]]
 author={'schemaVersion':'t66-authoring-family-record-v1','id':ident+'-AUTHORING','sourceFamilyId':fid,'side':side,'rights':p['rights'],'supportedSubjectKeys':[key],'motorRoleSourceKeys':[key],'anatomicalMotorRoleClaimed':True,'scope':'exact_source_rectus_knee_extension_native_complete_context','sourceGeometryModified':False,'measuredAnatomicalAxis':False,'measuredAttachmentFootprints':False,'poseRange':pose,'motionSha256':geometry['motionSha256'],'restSha256':geometry['restSha256'],'sourceManifestSha256':p['dataset']['sha256'],'sourceOverlaySha256':sha((ROOT/'atlas-data/overlays/za-local-integration.json').read_bytes()),'geometryRecordPath':str((dest/'geometry-record.json').relative_to(ROOT)),'contactQcPath':str((dest/'contact-qc.json').relative_to(ROOT)),'glbPoseQcPath':str((dest/'glb-pose-qc.json').relative_to(ROOT)),'glbInterpolationQcPaths':outcome['geometryQcPaths'],'actionOutcomePath':str((OUT/'knee-action-outcome.json').relative_to(ROOT)),'claims':claims,'qualitativeDirectionEvidence':p['family']['qualitativeEvidence'],'cooperativeMotionLimits':p['family']['unresolved']}
 for field,roles in [('movingBoneKeys',['moving_structure']),('fixedBoneKeys',['fixed_structure']),('coMovingContextKeys',['co_moving_context']),('passiveDeformationKeys',['deforming_passive_surface'])]:author[field]=[m['sourceKey'] for m in geometry['members'] if m['role'] in roles]
 deps=[uri,refuri,p['dataset']['path'],'atlas-data/overlays/za-local-integration.json',author['geometryRecordPath'],author['contactQcPath'],author['glbPoseQcPath'],author['actionOutcomePath'],*author['glbInterpolationQcPaths'].values(),str((dest/'input.json').relative_to(ROOT))]
 author['verificationDependencies']=[{'path':dep,'sha256':sha((ROOT/dep).read_bytes())} for dep in deps];ar=save(ROOT/f'atlas-data/motion/authoring/{ident.lower()}.json',author);reg['records'].append({'id':author['id'],'path':ar,'sha256':sha((ROOT/ar).read_bytes())})
 scene.update(id=ident+'-REFERENCE',assetUri=refuri,sourceAssetSha256=author['restSha256']);scenes['sceneManifests'].append(scene)
 definition.update(id=ident+'-MOTION',actionId=ident+'-ACTION',sourceFamilyId=fid,movingStructureIds=author['movingBoneKeys'],fixedStructureIds=author['fixedBoneKeys'],endPoseId=pose['endPoseId']);definition['staticReference'].update(sceneId=scene['id'],sourceAssetSha256=author['restSha256']);definition['poseSourceRefs']=[{'layer':'authoring_record','field':'motion_pose_range','appliesTo':'motion_pose_range','contextId':None,'claimId':author['id'],'valueHash':vhash(pose),'evidenceId':author['id'],'fieldEvidenceId':None}]
 asset.update(id=ident+'-ASSET',motionDefinitionId=definition['id'],uri=uri,revision='t66-priority-knee-extension-native-r1',sha256=author['motionSha256']);asset['staticBinding'].update(sceneId=scene['id'],sourceAssetSha256=author['restSha256']);asset['rig']={'id':ident+'-RIG','nodeBindings':[{'structureId':m['sourceKey'],'nodeId':m['nodeId']} for m in geometry['members'] if m['role']=='moving_structure']};asset['sourceBinding'].update(sourceFamilyId=fid,members=geometry['members']);asset['clip'].update(id=p['clipId'],durationSeconds=3,endPoseId=pose['endPoseId']);asset['poseControl']={'label':'무릎 굽힘 각도','startDegrees':0,'endDegrees':15,'combination':'single_dof_only','actionDirection':'reverse'}
 action={'id':ident+'-ACTION','subjectKind':'muscle','subjectIds':[],'sourceSubjectKeys':[key],'sideApplicability':side,'jointBindingState':'source_family_bound','sourceFamilyId':fid,'jointBindingNote':'Exact native rectus extension outcome with explicit preparation and direction; local authored education only','targetJointIds':[],'actionLabel':'무릎 폄 · 슬관절 신전','explanation':explanation,'postureConditions':[posture],'stabilizationConditions':[],'stabilizationNote':'주변 근육의 힘이나 생리적 활성도는 표시하지 않습니다.','contextRoles':[{'contextId':ident+'-CONTEXT','role':'unspecified','contractionRole':'unspecified','explanation':context}],'sourceRefs':[{'layer':'source_family_record','field':c['field'],'appliesTo':c['appliesTo'],'contextId':c['contextId'],'claimId':c['id'],'valueHash':vhash(c['value']),'evidenceId':author['id'],'fieldEvidenceId':None} for c in claims],'legacyJointActionId':None}
 # Prefer extension when rectus is selected, while retaining the separately verified hip action.
 index=next(i for i,a in enumerate(b['muscleActions']) if a['id']=='T66-PRIORITY-'+side[0].upper()+'-RECTUS-ACTION');b['muscleActions'].insert(index,action);b['motionDefinitions'].append(definition);b['motionAssets'].append(asset);pol['productionMotionAssetIds'].append(asset['id'])
 accept['rows'].append({'actionId':action['id'],'assetId':asset['id'],'sourceKey':key,'side':side,'motionSha256':asset['sha256'],'authoringPath':ar,'authoringSha256':sha((ROOT/ar).read_bytes()),'outcomePath':author['actionOutcomePath'],'outcomeSha256':sha((ROOT/author['actionOutcomePath']).read_bytes())})
for path,value in [('atlas-data/motion/motion-learning.json',b),('atlas-data/motion/motion-scenes.json',scenes),('atlas-data/motion/authoring/registry.json',reg),('atlas-data/motion/motion-asset-sources.json',pol),('atlas-data/motion/t66-priority-action-acceptance.json',accept)]:save(ROOT/path,value)
print('registered bilateral extension with separate preparation and full context')
