"""Register only the three newly accepted exact source/action selectors; preserve all predecessors."""
import json,pathlib,copy,hashlib,math
ROOT=pathlib.Path(__file__).resolve().parents[4];OUT=pathlib.Path(__file__).parent
load=lambda p:json.loads((ROOT/p).read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
enc=lambda v:(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False)+'\n').encode()
vhash=lambda v:sha(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'),allow_nan=False).encode())
def save(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(enc(v));return str(p.relative_to(ROOT))
def dep(p):return {'path':p,'sha256':sha((ROOT/p).read_bytes())}
bundle=load('atlas-data/motion/motion-learning.json');registry=load('atlas-data/motion/authoring/registry.json');scenes=load('atlas-data/motion/motion-scenes.json');sources=load('atlas-data/motion/motion-asset-sources.json');outcomes=load(str((OUT/'action-outcome.json').relative_to(ROOT)))
assert all(r['passed'] for r in outcomes) and len(outcomes)==4
if any(a['id'].startswith('T66-PRIORITY-') for a in bundle['motionAssets']):raise RuntimeError('already registered: do not duplicate')
proof=save(OUT/'qualitative-action-evidence.json',{'sourceUrl':'https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/muscle-tables/muscles-of-the-lower-limb/','accessedOn':'2026-10-05','locator':'rectus femoris row: origin, insertion, action and quadriceps note; tibialis anterior row: action','paraphraseKo':{'rectus':'대퇴직근은 고관절 굽힘과 무릎 폄에 관여하며, 골반에서 시작해 무릎뼈와 무릎인대를 거쳐 정강뼈거친면에 이어지는 두 관절 근육입니다.','tibialis':'앞정강근은 발목 등쪽굽힘과 발 안쪽번짐에 관여합니다. 이번 시범은 등쪽굽힘만 구현합니다.'},'scope':'qualitative anatomy only, no source coordinates/footprints/physiological contraction or ROM','existingAttachmentRecord':'atlas-data/terminology/muscle-attachment-content-2026-10-02.json'})
accepted=[];registrations=[]
for outcome in outcomes:
 side=outcome['side'];kind=outcome['kind'];key=outcome['sourceKey']
 if side=='right' and kind=='tibialis':continue
 ident='T66-PRIORITY-'+('L' if side=='left' else 'R')+('-TIBANT' if kind=='tibialis' else '-RECTUS')
 if kind=='tibialis':
  candidate=OUT/'left-tibialis';geom=load(str((candidate/'family-geometry-record.json').relative_to(ROOT)));old=load(str((candidate/'authoring-record.json').relative_to(ROOT)));family=geom['family'];fid=family['id'];authorid=ident+'-AUTHORING';pose={**old['poseRange'],'endDegrees':6.5}
  asset=copy.deepcopy(next(a for a in bundle['motionAssets'] if a['id']=='T59-ASSET-ZA-R-TIBANT-DF'))
  uri=f'atlas-data/assets/motion/t66-priority-left-tibialis/motion.glb';refuri='atlas-data/assets/derived-glb/t66-priority-left-tibialis/reference.glb'
  for p,src in [(ROOT/uri,candidate/'motion.glb'),(ROOT/refuri,candidate/'reference.glb')]:p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(src.read_bytes())
  author={'schemaVersion':'t66-authoring-family-record-v1','id':authorid,'sourceFamilyId':fid,'side':side,'rights':old['rights'],'poseRange':pose,'motionSha256':old['motionSha256'],'restSha256':old['restSha256'],'measuredAnatomicalAxis':False,'measuredAttachmentFootprints':False,'sourceGeometryModified':False,'scope':'exact_source_muscle_action_educational','supportedSubjectKeys':[key],'movingBoneKeys':[m['sourceKey'] for m in geom['members'] if m['role']=='moving_structure'],'fixedBoneKeys':[m['sourceKey'] for m in geom['members'] if m['role']=='fixed_structure'],'coMovingContextKeys':[m['sourceKey'] for m in geom['members'] if m['role']=='co_moving_context'],'passiveDeformationKeys':[m['sourceKey'] for m in geom['members'] if m['role']=='deforming_passive_surface'],'geometryRecordPath':str((candidate/'family-geometry-record.json').relative_to(ROOT)),'contactQcPath':str((candidate/'contact-qc.json').relative_to(ROOT)),'glbPoseQcPath':str((candidate/'glb-pose-qc.json').relative_to(ROOT)),'glbInterpolationQcPaths':{m['sourceKey']:str((candidate/('interpolation-'+m['sourceKey']+'.json')).relative_to(ROOT)) for m in geom['members'] if m['role'].startswith('deforming')},'qualitativeDirectionEvidence':old['anatomicalEvidence'],'geometryInspection':old['geometryInspection'],'sourceManifestSha256':sha((ROOT/'atlas-data/source-cache/datasets/za/compiled/manifest.json').read_bytes()),'sourceOverlaySha256':sha((ROOT/'atlas-data/overlays/za-local-integration.json').read_bytes())}
  scene={**copy.deepcopy(next(x for x in scenes['sceneManifests'] if x['id']==asset['staticBinding']['sceneId'])),'id':ident+'-REFERENCE','assetUri':refuri,'sourceAssetSha256':author['restSha256'],'side':side,'poseId':pose['referencePoseId']};scenes['sceneManifests'].append(scene)
  asset['staticBinding'].update(sceneId=scene['id'],side=side,sourceAssetSha256=author['restSha256']);asset['rig']['nodeBindings']=[{'structureId':m['sourceKey'],'nodeId':m['nodeId']} for m in geom['members'] if m['role']=='moving_structure'];asset['sourceBinding'].update(subjectKind='muscle',contractVersion='t66-typed-source-motion-v2',subjectSourceKey=key,sourceFamilyId=fid,members=geom['members']);asset['poseControl']={'label':'発목 등쪽굽힘'.replace('発','발'),'startDegrees':0,'endDegrees':6.5,'combination':'single_dof_only'};asset['clip'].update(id='T66-PRIORITY-L-TIBANT-DF6P5',endPoseId=pose['endPoseId'])
  static={'sceneId':scene['id'],'sceneRevision':scene['revision'],'modelId':scene['modelId'],'sourceAssetSha256':author['restSha256'],'frameId':scene['frameId'],'units':'m','poseId':pose['referencePoseId']}
  definition={'id':ident+'-MOTION','actionId':ident+'-ACTION','instanceId':key,'side':side,'sourceFamilyId':fid,'targetJointIds':[],'movingStructureIds':author['movingBoneKeys'],'fixedStructureIds':author['fixedBoneKeys'],'staticReference':static,'startPoseId':pose['referencePoseId'],'endPoseId':pose['endPoseId']}
  label='발목 등쪽굽힘';explanation='앞정강근이 발등을 정강이 쪽으로 들어 올리는 작용을 봅니다. 정강뼈·종아리뼈는 고정하고 발의 뼈와 연결된 근육 표면은 함께 움직입니다. 실제 힘이나 수축량을 계산하는 시범은 아닙니다.'
 else:
  baseasset=next(a for a in bundle['motionAssets'] if a.get('sourceBinding',{}).get('subjectSourceKey')==key and a.get('sourceBinding',{}).get('sourceFamilyId')==f'hip-flexion-{side}');asset=copy.deepcopy(baseasset);definition=copy.deepcopy(next(x for x in bundle['motionDefinitions'] if x['id']==asset['motionDefinitionId']));original=load(f'atlas-data/motion/authoring/t66-unit02-hip-flexion-{side}.json')
  # All actual buffers stay byte-identical. New semantic acceptance is confined to rectus and supported by emitted outcome/attachment checks.
  for d in original['verificationDependencies']:assert sha((ROOT/d['path']).read_bytes())==d['sha256'],d['path']
  fid=f'priority-rectus-hip-flexion-{side}';author=copy.deepcopy(original);authorid=ident+'-AUTHORING';author.update(id=authorid,sourceFamilyId=fid,supportedSubjectKeys=[key],scope='exact_rectus_source_action_hip_flexion_knee_held',anatomicalMotorRoleClaimed=True,motorRoleSourceKeys=[key]);author['passiveDeformationKeys']=[k for k in author['passiveDeformationKeys'] if k!=key]
  geo=load(original['geometryRecordPath']);geo['family']['id']=fid;geo['id']=authorid
  for m in geo['members']+geo['surfaceMetrics']:
   if m['sourceKey']==key:m['role']='deforming_muscle_surface'
  qp=load(original['glbPoseQcPath']);qp['familyId']=fid
  targetdir=OUT/('rectus-'+side);author['geometryRecordPath']=save(targetdir/'geometry-record.json',geo);author['glbPoseQcPath']=save(targetdir/'glb-pose-qc.json',qp)
  author['reuseReceipt']={'originalAuthoringPath':f'atlas-data/motion/authoring/t66-unit02-hip-flexion-{side}.json','originalAuthoringSha256':sha((ROOT/f'atlas-data/motion/authoring/t66-unit02-hip-flexion-{side}.json').read_bytes()),'unchangedMotionGlbSha256':asset['sha256'],'unchangedReferenceGlbSha256':author['restSha256'],'newReview':'actual source-specific fixed/moving masks, shortening, forward thigh trajectory, held knee and patella/quadriceps context','passiveSelectorsPreserved':True,'recomputedOtherFamilyGeometry':False}
  for m in asset['sourceBinding']['members']:
   if m['sourceKey']==key:m['role']='deforming_muscle_surface'
  asset['sourceBinding']['sourceFamilyId']=fid;definition.update(id=ident+'-MOTION',actionId=ident+'-ACTION',sourceFamilyId=fid)
  uri=asset['uri'];label='고관절 굽힘 · 무릎 유지';explanation='대퇴직근이 허벅지를 앞으로 들어 올리는 고관절 굽힘 작용을 봅니다. 골반 쪽은 고정되고 무릎뼈·정강뼈가 허벅지와 함께 움직이며 무릎 각도는 유지됩니다. 대퇴직근은 무릎을 펴는 작용도 하지만, 이 시범에는 무릎 폄을 섞지 않았습니다.'
  author['cooperativeMotionLimits']+=['Rectus only has qualitative hip-flexor action acceptance; the other quadriceps surfaces remain passive context.','Knee/patella relative pose is held. No independent patellar tracking, tendon mesh, force or measured contraction is asserted.']
 author['claims']=[{'id':ident+'-ACTION-FIELD','field':'action','appliesTo':'action_explanation','contextId':None,'value':explanation}]
 author['qualitativeActionEvidencePath']=proof;author['actionOutcomePath']=str((OUT/'action-outcome.json').relative_to(ROOT));author['anatomicalMotorRoleClaimed']=True;author['motorRoleSourceKeys']=[key]
 paths=list(dict.fromkeys([d['path'] for d in author.get('verificationDependencies',[])]+[author['geometryRecordPath'],author['contactQcPath'],author['glbPoseQcPath'],*author.get('glbInterpolationQcPaths',{}).values(),proof,author['actionOutcomePath'],uri,'atlas-data/source-cache/datasets/za/compiled/manifest.json','atlas-data/overlays/za-local-integration.json']))
 author['verificationDependencies']=[dep(p) for p in paths]
 ar=save(ROOT/f'atlas-data/motion/authoring/{ident.lower()}.json',author);registry['records'].append({'id':authorid,'path':ar,'sha256':sha((ROOT/ar).read_bytes())})
 action={'id':ident+'-ACTION','subjectKind':'muscle','subjectIds':[],'sourceSubjectKeys':[key],'sideApplicability':side,'jointBindingState':'source_family_bound','sourceFamilyId':fid,'jointBindingNote':'Exact native source action with independently checked qualitative attachments and emitted outcome; no canonical/full-target/physiological approval.','targetJointIds':[],'actionLabel':label,'explanation':explanation,'postureConditions':[],'stabilizationConditions':[],'stabilizationNote':'주변 조직의 공동 이동은 개별 근육의 활성도나 안정화 기여도를 뜻하지 않습니다.','contextRoles':[],'sourceRefs':[{'layer':'source_family_record','field':'action','appliesTo':'action_explanation','contextId':None,'claimId':ident+'-ACTION-FIELD','valueHash':vhash(explanation),'evidenceId':authorid,'fieldEvidenceId':None}],'legacyJointActionId':None}
 definition['poseSourceRefs']=[{'layer':'authoring_record','field':'motion_pose_range','appliesTo':'motion_pose_range','contextId':None,'claimId':authorid,'valueHash':vhash(author['poseRange']),'evidenceId':authorid,'fieldEvidenceId':None}]
 asset.update(id=ident+'-ASSET',motionDefinitionId=definition['id'],uri=uri,sha256=author['motionSha256'],revision='t66-priority-ankle-knee-2026-10-05-r1');asset['sourceBinding']['sourceOverlaySha256']=author['sourceOverlaySha256']
 bundle['muscleActions'].append(action);bundle['motionDefinitions'].append(definition);bundle['motionAssets'].append(asset);sources['productionMotionAssetIds'].append(asset['id'])
 accepted.append({'actionId':action['id'],'assetId':asset['id'],'sourceKey':key,'side':side,'motionSha256':asset['sha256'],'authoringPath':ar,'authoringSha256':sha((ROOT/ar).read_bytes()),'outcomePath':author['actionOutcomePath'],'outcomeSha256':sha((ROOT/author['actionOutcomePath']).read_bytes())});registrations.append({'sourceKey':key,'side':side,'assetId':asset['id'],'familyId':fid,'uri':uri,'newGlb':kind=='tibialis'})
for p,v in [('atlas-data/motion/motion-learning.json',bundle),('atlas-data/motion/authoring/registry.json',registry),('atlas-data/motion/motion-scenes.json',scenes),('atlas-data/motion/motion-asset-sources.json',sources)]:save(ROOT/p,v)
save(ROOT/'atlas-data/motion/t66-priority-action-acceptance.json',{'schemaVersion':'t66-priority-action-acceptance-v1','acceptanceScope':'exact_source_action_educational_local_only','publicRedistribution':'held','humanReview':'not_performed','rows':accepted})
save(OUT/'registration.json',registrations);print('Registered',len(accepted),'new exact source/action selectors; 1 new motion GLB, 2 unchanged hip GLBs reused')
