import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {wholeBodyPlugin} from '../plugins/wholeBody.ts';
import {readDatasetRoute} from '../src/viewer/datasets/integration.ts';
const root=fileURLToPath(new URL('../../',import.meta.url));const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
let handler:any;const watcher={add:()=>{},on:()=>watcher,off:()=>{}};
(wholeBodyPlugin(root).configureServer as Function)({watcher,middlewares:{use:(f:any)=>handler=f},httpServer:{once:()=>{}}});
async function get(url:string){return new Promise<Buffer>((resolve,reject)=>{const res={statusCode:200,setHeader:()=>{},end:(b:any)=>{if(res.statusCode!==200)reject(Error(url+': '+res.statusCode));else resolve(Buffer.from(b))}};Promise.resolve(handler({url,headers:{},destroyed:false},res,()=>reject(Error('missing route')))).catch(reject)})}
const runtimeBytes=await get('/__atlas/integration.json'),datasetBytes=await get('/__atlas/datasets/human-atlas-local/manifest.json');
const runtime=JSON.parse(runtimeBytes.toString()),dataset=JSON.parse(datasetBytes.toString());
const base=JSON.parse(await readFile(root+'atlas-data/overlays/za-local-integration.json','utf8'));
const nav=JSON.parse(await readFile(root+'atlas-data/navigation/atlas-navigation.json','utf8')).categories.map((c:any)=>c.id);
const nerves=runtime.objects.filter((r:any)=>r.kind==='nerve');assert.equal(nerves.length,6);
for(const n of nerves){assert.equal(readDatasetRoute('?source='+n.sourceKey,runtime.objects,nav).selected,n.sourceKey);assert.equal(n.haConceptId,null);assert.equal(n.sourceOnly,true);assert.equal(n.humanReview,'not_performed');assert.equal(n.publicRedistribution,'held');}
for(const r of base.objects){const row=runtime.objects.find((n:any)=>n.sourceKey===r.sourceKey);assert.equal(row.haConceptId,r.haConceptId);assert.equal(row.kind,r.kind);assert.deepEqual(row.names,r.names);assert.deepEqual(row.regionIds,r.regionIds);assert.deepEqual(row.bounds,r.bounds);assert.deepEqual(row.sourceHiddenStatePreserved,r.sourceHiddenStatePreserved);assert.equal(row.localDisplayEligible,r.localDisplayEligible);}
const report={taskId:'T63',contractRevision:'app-completion-2026-10-01',acceptanceScope:'six same-source static fibular nerve surfaces, typed routes/cards/branch navigation and two side-matched tibialis-anterior motor relations in one existing learner scene; no universal extent or dynamic pose',productReadiness:'local_app_ready',contentCompleteness:'partial',unresolvedProductBlockers:[],runtime:{sha256:sha(runtimeBytes),records:runtime.objects.length,learnerEligible:runtime.objects.filter((r:any)=>r.routeAudience==='learner'&&r.localDisplayEligible).length,inspectionEligible:runtime.objects.filter((r:any)=>r.routeAudience==='inspection'&&r.localDisplayEligible).length,existingCanonicalHaBindings:runtime.objects.filter((r:any)=>r.haConceptId!==null).length},dataset:{sha256:sha(datasetBytes),...dataset.metrics},denominators:runtime.scope,nerveSupport:{instances:6,searchGroups:new Set(nerves.map((n:any)=>n.searchGroupKey)).size,staticPoseIds:[...new Set(nerves.map((n:any)=>n.nerve.poseId))],supportedContextRegions:[...new Set(nerves.flatMap((n:any)=>n.regionIds))],visibleBranchEdges:nerves.reduce((v:number,n:any)=>v+n.nerve.branchKeys.length,0),motorEdges:nerves.reduce((v:number,n:any)=>v+n.nerve.muscleKeys.length,0),newHaBindings:0},basePreservation:{zaRecordsCompared:base.objects.length,namesSidesRegionsBoundsEligibilityAndHaUnchanged:true,allSixNerveRoutesValidated:true},impactAnalysis:{sourceOnly:true,publicRedistribution:'held',humanReview:'not_performed',regionMeaning:'display_context_only; source surfaces not clipped to region',existingG1Scope:'Frozen T58 target/member coverage preserved; G3 nerve support is a separate extension, not added to the 542/563 denominator.',geometrySpace:'Domain source_world: original object transform baked into native ZA coordinates. Existing technical dataset source_local denotes the source namespace coordinate frame, with only the ZA-to-atlas axis matrix on the instance. No inter-model alignment or double transform.',visualReuse:'Existing bone/muscle geometry, names, side, target routes and shader colors preserved; T58 region captures reused after exact input comparison. T63 exercises 12 actual regional UI transitions and new nerve cases. T63 viewer option layout and typed nerve rendering have fresh 1440/1024/390 evidence.'}};
await writeFile(root+'work/evidence/T63/product-scope.json',JSON.stringify(report,null,2)+'\n');
await writeFile(root+'work/evidence/T63/browser/runtime.json',runtimeBytes);await writeFile(root+'work/evidence/T63/browser/dataset.json',datasetBytes);
console.log(JSON.stringify({runtime:report.runtime,nerveSupport:report.nerveSupport,dataset:report.dataset}));
