import {createRequire} from 'node:module';import {writeFile,mkdir} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';
const require=createRequire('/Users/daniel/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/t58.cjs');const {chromium}=require('playwright');const out=resolve('../work/evidence/T58/app-finish-2026-10-01/context-final');await mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:5178/');const wait=async()=>{await page.waitForFunction(()=>{const e=document.querySelector('canvas');if(!e?.dataset.dataset)return false;const s=JSON.parse(e.dataset.dataset);return s.pending===0&&s.visible.length>0;});await page.waitForTimeout(700);};await wait();const root=await page.locator('canvas').getAttribute('id');
const rows=await page.evaluate(async()=> (await(await fetch('/__atlas/integration.json')).json()).objects);
for(const [id,label,rx,count] of [['neck','목',/^Vertebra C|^Atlas \(C1\)|^Axis \(C2\)/,7],['thorax','가슴우리',/^Vertebra T/,12],['abdomen-lumbar','배·허리',/^Vertebra L/,5]]){
 await page.locator('.region-all-toggle').click();await page.getByRole('button',{name:label,exact:true}).click();await wait();await page.getByRole('button',{name:'근육',exact:true}).click();await wait();
 const state=await page.locator('canvas').evaluate(e=>JSON.parse(e.dataset.dataset));const bones=rows.filter(r=>r.localDisplayEligible&&rx.test(r.names.en));const png=await page.screenshot({path:resolve(out,id+'-bones.png')});
 results.push({region:id,pass:bones.length===count&&bones.every(r=>state.visible.includes(r.sourceKey))&&state.visible.every(k=>rows.find(r=>r.sourceKey===k)?.kind==='bone'),visibleBones:state.visible.length,vertebrae:count,screenshot:id+'-bones.png',sha256:createHash('sha256').update(png).digest('hex')});await page.getByRole('button',{name:'근육',exact:true}).click();await wait();
}
await page.locator('.region-all-toggle').click();await page.getByRole('button',{name:'등',exact:true}).click();await wait();await page.locator('canvas').focus();for(let i=0;i<26;i++)await page.keyboard.press('ArrowLeft');await page.waitForTimeout(1000);const png=await page.screenshot({path:resolve(out,'back-posterior.png')});results.push({view:'back-posterior',pass:await page.locator('canvas').getAttribute('id')===root,screenshot:'back-posterior.png',sha256:createHash('sha256').update(png).digest('hex')});await browser.close();await writeFile(resolve(out,'context-validation.json'),JSON.stringify({results,errors,fullTargetExtentAccepted:0},null,2)+'\n');console.log(JSON.stringify({passed:results.every(r=>r.pass)&&errors.length===0,results:results.length,errors}));if(results.some(r=>!r.pass)||errors.length)process.exitCode=1;
