"""Adopt only emitted, independently inspected exact-source trunk muscle actions."""
import pathlib,sys,json,copy,hashlib,shutil
import numpy as np
R=pathlib.Path(__file__).resolve().parents[4];O=pathlib.Path(__file__).parent
sys.path[:0]=[str(R/'work/tools'),str(R/'work/evidence/T66/serial-completion-2026-10-02/unit-01')]
from verify_glb_interpolation import read_glb,channel_data,node_positions
load=lambda p:json.loads((R/p).read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
def save(p,v):
 p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False)+'\n');return str(p.relative_to(R))
def dep(p):return {'path':p,'sha256':sha((R/p).read_bytes())}
def vhash(v):return sha(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
b=load('atlas-data/motion/motion-learning.json');reg=load('atlas-data/motion/authoring/registry.json');sc=load('atlas-data/motion/motion-scenes.json');policy=load('atlas-data/motion/motion-asset-sources.json');accept=load('atlas-data/motion/t66-priority-action-acceptance.json');src={r['sourceKey']:r for r in load('atlas-data/source-cache/datasets/za/compiled/manifest.json')['instances']};names={r['name']:k for k,r in src.items()}
assert not any(a['id'].startswith('T66-PRIORITY-S04-') for a in b['motionAssets'])
template=next(a for a in b['motionAssets'] if a['id']=='T66-PRIORITY-S03-L-LEV-LEV-ASSET');td=next(d for d in b['motionDefinitions'] if d['id']==template['motionDefinitionId']);ts=next(s for s in sc['sceneManifests'] if s['id']==template['staticBinding']['sceneId']);tar=load(next(r['path'] for r in reg['records'] if r['id']=='T66-PRIORITY-S03-L-LEV-AUTHORING'));outcomes=[];registrations=[];authors=[]
for side in ['left','right']:
 for kind in ['RECTUS','OBLIQUE']:
  source=names[('Rectus abdominis muscle' if kind=='RECTUS' else 'External abdominal oblique muscle')+'.'+side[0]];motionkind='flex';dest=O/motionkind;c=load(str((dest/'complete.json').relative_to(R)));geo=load(str((dest/'geometry-record.json').relative_to(R)));pose=load(str((dest/'glb-pose-qc.json').relative_to(R)));inp=load(str((dest/'authored-input.json').relative_to(R)));ident='T66-PRIORITY-S04-'+side[0].upper()+'-'+kind;fid='priority-trunk-'+kind.lower()+'-'+side
  assert pose['passed'] and load(str((dest/'contact-qc.json').relative_to(R)))['passed']
  assert load(str((dest/'rigid-context-audit.json').relative_to(R)))['passed']
  uri='atlas-data/assets/motion/t66-priority-s04-'+motionkind+'/motion.glb';refuri='atlas-data/assets/derived-glb/t66-priority-s04-'+motionkind+'/reference.glb'
  for p,filename in [(uri,'motion.glb'),(refuri,'reference.glb')]:path=R/p;path.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(dest/filename,path)
  geo['family']['referencePoseId']=template['sourceBinding']['referencePoseId']
  raw,doc,buf=read_glb(R/uri);assert sha(raw)==c['motionSha256'];tracks=channel_data(doc,buf);nodes={n['extras']['sourceKey']:i for i,n in enumerate(doc['nodes'])};poses=[node_positions(doc,buf,tracks,nodes[source],float(t)) for t in np.linspace(0,2.5,65)];entry=next(e for e in inp['surfaceFields'] if e['sourceKey']==source);fixed=entry['fixedVertexIndices'];moving=entry['movingVertexIndices'];assert fixed and moving
  span=lambda w:float(np.linalg.norm(w[fixed].mean(0)-w[moving].mean(0)));spans=[span(w) for w in poses];error=max(float(np.linalg.norm(w[fixed]-poses[0][fixed],axis=1).max()) for w in poses);shortening=spans[0]-spans[-1]
  stern=names['Body of sternum'];s0=node_positions(doc,buf,tracks,nodes[stern],0).mean(0);s1=node_positions(doc,buf,tracks,nodes[stern],2.5).mean(0);ds=s1-s0;pelviserror=max(float(np.linalg.norm(node_positions(doc,buf,tracks,nodes[names['Hip bone.'+s]],t)-node_positions(doc,buf,tracks,nodes[names['Hip bone.'+s]],0),axis=1).max()) for s in ['l','r'] for t in np.linspace(0,2.5,65))
  assert error<1e-6 and pelviserror<1e-6 and shortening>.0005,(side,kind,error,shortening,ds)
  assert all(a-b>=-1e-6 for a,b in zip(spans,spans[1:])),(side,kind,spans)
  assert ds[2]>.02 and ds[1]<-.005,ds
  outcome={'sourceKey':source,'side':side,'kind':kind,'assetId':ident+'-ASSET','motionSha256':c['motionSha256'],'passed':True,'actionDirection':'forward','shorteningMetres':shortening,'fixedMaskErrorMetres':error,'pelvisFixedErrorMetres':pelviserror,'sternumDisplacementMetres':ds.tolist(),'surfaceExcursionMetres':max(float(np.linalg.norm(w-poses[0],axis=1).max()) for w in poses),'inspectedPoseSamples':65,'contextSurfaceCount':len(c['members']),'physiologicalContractionClaimed':False,'measuredAttachmentFootprints':False,'geometryQcPath':c['glbInterpolationQcPaths'][source]};outcomes.append(outcome)
  label='몸통 굽힘' if kind=='RECTUS' else '양측 협응 몸통 굽힘';explanation='골반을 유지하면서 흉곽이 골반 쪽으로 가까워지는 복직근의 대표 작용을 봅니다. 양쪽 복직근과 주변 배 근육이 함께 변형되며 척추 분절과 흉곽이 따라 움직입니다.' if kind=='RECTUS' else '양쪽 외복사근이 함께 관여하는 몸통 굽힘을 보여줍니다. 넓은 배바깥빗근 표면과 주변 배 근육이 함께 변형됩니다. 한쪽 외복사근이 관여하는 반대 방향 몸통 돌림과 구분되는 시범입니다.'
  condition='골반을 유지한 교육용 시범입니다. 각도와 표면 변형은 학습을 위해 작성했으며 개인의 정상 가동범위·힘·활성도나 정확한 관절축을 뜻하지 않습니다.';context='척추·갈비뼈·골반과 주변 근육의 온전한 표면을 함께 관찰합니다. 주변 표면의 움직임은 개별 근육이 힘을 내는 정도를 표시하지 않습니다.'
  contract=O/(kind.lower()+'-'+side);geo=copy.deepcopy(geo);geo['family']['id']=fid;pose=copy.deepcopy(pose);pose['familyId']=fid;members=copy.deepcopy(c['members']);motors=[names[('Rectus abdominis muscle' if kind=='RECTUS' else 'External abdominal oblique muscle')+'.'+s] for s in ['l','r']]
  for m in members+geo['members']+geo['surfaceMetrics']:
   if m['sourceKey'] in motors:m['role']='deforming_muscle_surface'
   elif m['sourceKey'] in c['glbInterpolationQcPaths']:m['role']='deforming_passive_surface'
  author={'schemaVersion':'t66-authoring-family-record-v1','id':ident+'-AUTHORING','sourceFamilyId':fid,'side':side,'rights':copy.deepcopy(tar['rights']),'sourceGeometryModified':False,'measuredAnatomicalAxis':False,'measuredAttachmentFootprints':False,'anatomicalMotorRoleClaimed':True,'scope':'exact_native_source_bilateral_trunk_flexion_teaching_action','supportedSubjectKeys':[source],'motorRoleSourceKeys':motors,'poseRange':{**geo['family'],'meaning':condition,'actionDirection':'forward'},'movingBoneKeys':[m['sourceKey'] for m in members if m['role']=='moving_structure'],'fixedBoneKeys':[m['sourceKey'] for m in members if m['role']=='fixed_structure'],'coMovingContextKeys':[m['sourceKey'] for m in members if m['role']=='co_moving_context'],'passiveDeformationKeys':[m['sourceKey'] for m in members if m['role']=='deforming_passive_surface'],'motionSha256':c['motionSha256'],'restSha256':c['restSha256'],'sourceManifestSha256':sha((R/'atlas-data/source-cache/datasets/za/compiled/manifest.json').read_bytes()),'sourceOverlaySha256':sha((R/'atlas-data/overlays/za-local-integration.json').read_bytes()),'geometryRecordPath':save(contract/'geometry-record.json',geo),'glbPoseQcPath':save(contract/'glb-pose-qc.json',pose),'contactQcPath':str((dest/'contact-qc.json').relative_to(R)),'glbInterpolationQcPaths':c['glbInterpolationQcPaths'],'actionOutcomePath':str((O/'action-outcome.json').relative_to(R)),'qualitativeActionEvidencePath':str((O/'qualitative-action-evidence.json').relative_to(R))}
  author['claims']=[{'id':ident+'-'+f,'field':f,'appliesTo':scope,'contextId':cid,'value':v} for f,scope,cid,v in [('action','action_explanation',None,explanation),('model_posture','posture_condition',None,condition),('model_context','context_role',ident+'-CONTEXT',context)]]
  scene=copy.deepcopy(ts);scene.update(id=ident+'-REFERENCE',assetUri=refuri,sourceAssetSha256=c['restSha256'],side=side,poseId=geo['family']['referencePoseId']);sc['sceneManifests'].append(scene);act={'id':ident+'-ACTION','subjectKind':'muscle','subjectIds':[],'sourceSubjectKeys':[source],'sideApplicability':side,'jointBindingState':'source_family_bound','sourceFamilyId':fid,'jointBindingNote':'Exact native source educational action; group/canonical/physiological approval not inferred','targetJointIds':[],'actionLabel':label,'explanation':explanation,'postureConditions':[condition],'stabilizationConditions':[],'stabilizationNote':context,'contextRoles':[{'contextId':ident+'-CONTEXT','role':'unspecified','contractionRole':'unspecified','explanation':context}],'sourceRefs':[{'layer':'source_family_record','field':claim['field'],'appliesTo':claim['appliesTo'],'contextId':claim['contextId'],'claimId':claim['id'],'valueHash':vhash(claim['value']),'evidenceId':author['id'],'fieldEvidenceId':None} for claim in author['claims']],'legacyJointActionId':None}
  d=copy.deepcopy(td);d.update(id=ident+'-MOTION',actionId=act['id'],instanceId=source,side=side,sourceFamilyId=fid,movingStructureIds=author['movingBoneKeys'],fixedStructureIds=author['fixedBoneKeys'],startPoseId=geo['family']['referencePoseId'],endPoseId=geo['family']['endPoseId']);d['staticReference'].update(sceneId=scene['id'],sourceAssetSha256=c['restSha256'],poseId=geo['family']['referencePoseId']);d['poseSourceRefs']=[{'layer':'authoring_record','field':'motion_pose_range','appliesTo':'motion_pose_range','contextId':None,'claimId':author['id'],'valueHash':vhash(author['poseRange']),'evidenceId':author['id'],'fieldEvidenceId':None}]
  asset=copy.deepcopy(template);asset.update(id=ident+'-ASSET',motionDefinitionId=d['id'],uri=uri,sha256=c['motionSha256'],revision='t66-priority-trunk-r1');asset['staticBinding'].update(sceneId=scene['id'],sourceAssetSha256=c['restSha256'],side=side,referencePoseId=geo['family']['referencePoseId']);asset['clip'].update(id=c['clipId'],durationSeconds=2.5,startPoseId=geo['family']['referencePoseId'],endPoseId=geo['family']['endPoseId']);asset['rig']['id']=ident+'-RIG';asset['rig']['nodeBindings']=[{'structureId':m['sourceKey'],'nodeId':m['nodeId']} for m in members if m['role']=='moving_structure'];asset['sourceBinding'].update(subjectSourceKey=source,sourceFamilyId=fid,members=members,sourceOverlaySha256=author['sourceOverlaySha256']);asset['poseControl']={'label':'몸통 굽힘 각도','startDegrees':0,'endDegrees':geo['family']['endDegrees'],'combination':'single_dof_only','actionDirection':'forward','observationDirection':[.8,.05,.6] if kind=='RECTUS' else [.3,.35,.88],'framingSourceKeys':[m['sourceKey'] for m in members if any(n in src[m['sourceKey']]['name'] for n in ['Rectus abdominis','External abdominal oblique','Hip bone','Sacrum','Vertebra L','Vertebra T12','Xiphoid'])],'contextOpacity':.25}
  b['muscleActions'].insert(0,act);b['motionDefinitions'].append(d);b['motionAssets'].append(asset);policy['productionMotionAssetIds'].append(asset['id']);authors.append((author,uri,str((dest/'authored-input.json').relative_to(R))));registrations.append({'sourceKey':source,'side':side,'kind':kind,'assetId':asset['id'],'actionId':act['id'],'familyId':fid,'uri':uri,'authoringId':author['id']})
op=save(O/'action-outcome.json',outcomes)
for author,uri,inputpath in authors:
 paths=[uri,inputpath,author['geometryRecordPath'],author['glbPoseQcPath'],author['contactQcPath'],*author['glbInterpolationQcPaths'].values(),op,author['qualitativeActionEvidencePath'],'atlas-data/source-cache/datasets/za/compiled/manifest.json','atlas-data/overlays/za-local-integration.json']
 candidate=(R/inputpath).parent
 paths.extend(str(p.relative_to(R)) for p in [candidate/'rigid-context-qc.json',candidate/'rigid-context-audit.json',*candidate.glob('*receipt*.json')])
 paths.extend(str(p.relative_to(R)) for p in [O/'author_trunk.py',O/'repair_interpolation.py',O/'repair_diaphragm_context.py',O/'compact_emitted.py',O/'compact_rest_reference.py',O/'verify_context.py',O/'audit_rigid_precision.py',O/'trunk_contact_patch.py',O/'qualitative-action-evidence.json'])
 for m in load(author['geometryRecordPath'])['members']:paths.append('atlas-data/source-cache/datasets/za/resources/'+src[m['sourceKey']]['lods']['overview']['resource']+'.glb')
 author['verificationDependencies']=[dep(p) for p in dict.fromkeys(paths)];ap=save(R/('atlas-data/motion/authoring/'+author['id'].lower()+'.json'),author);ah=sha((R/ap).read_bytes());reg['records'].append({'id':author['id'],'path':ap,'sha256':ah});r=next(r for r in registrations if r['authoringId']==author['id']);r['authoringPath']=ap;accept['rows'].append({'actionId':r['actionId'],'assetId':r['assetId'],'sourceKey':r['sourceKey'],'side':r['side'],'motionSha256':author['motionSha256'],'authoringPath':ap,'authoringSha256':ah,'outcomePath':op,'outcomeSha256':sha((R/op).read_bytes())})
for p,v in [('atlas-data/motion/motion-learning.json',b),('atlas-data/motion/motion-scenes.json',sc),('atlas-data/motion/authoring/registry.json',reg),('atlas-data/motion/motion-asset-sources.json',policy),('atlas-data/motion/t66-priority-action-acceptance.json',accept)]:save(R/p,v)
save(O/'registration.json',registrations);print('Registered four exact native source actions / one shared flexion GLB')
