import * as THREE from "./vendor/three/build/three.module.js";
import { GLTFLoader } from "./vendor/three/examples/jsm/loaders/GLTFLoader.js";
const canvas=document.querySelector('#canvas'),status=document.querySelector('#status'),list=document.querySelector('#list'),selectedText=document.querySelector('#selected');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x10151b,1);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x10151b);const camera=new THREE.PerspectiveCamera(35,1,.01,30);const root=new THREE.Group();root.name='AnatomySceneRoot';scene.add(root);scene.add(new THREE.HemisphereLight(0xe7f1ff,0x34404b,1.9));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(1.6,2.2,2.5);scene.add(key);const fill=new THREE.DirectionalLight(0xa9caff,1.1);fill.position.set(-2,1,-1.6);scene.add(fill);
const loader=new GLTFLoader(),targets=[],baseMaterials=new Map();let selected=-1,currentView='front',center=new THREE.Vector3(),distance=2,wholeBounds=new THREE.Box3();
const packageSpecs=[
 ...Array.from({length:9},(_,i)=>({id:`T52-B${String(i+1).padStart(2,'0')}`,path:`./assets/T52-B${String(i+1).padStart(2,'0')}.glb`})),
 {id:'T53',path:'./assets/T53-trunk-pelvis-static-source.glb'},
 {id:'T54',path:'./assets/T54-shoulder-upper-limb-static-source.glb'},
 {id:'T55',path:'./assets/T55-bilateral-lower-limb-static-source.glb'},
 {id:'T71',path:'./assets/T71-trunk-skeleton-static-source.glb'},
 {id:'T72',path:'./assets/T72-first-pass-residual-static-source.glb',targets:true},
];
function frame(){let w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera)}
function face(v){currentView=v;document.body.dataset.cameraView=v;let d={front:new THREE.Vector3(0,.08,1),back:new THREE.Vector3(0,.08,-1),side:new THREE.Vector3(1,.08,0)}[v];camera.position.copy(center).addScaledVector(d,distance);camera.lookAt(center);for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===v));if(window.t72QaProof)window.t72QaProof.views.push(v);frame()}
function focusObject(object){const box=new THREE.Box3().setFromObject(object);center=box.getCenter(new THREE.Vector3());const size=box.getSize(new THREE.Vector3());distance=Math.max(size.x,size.y,size.z)*2.2+.04}
function fitAll(){center=wholeBounds.getCenter(new THREE.Vector3());let s=wholeBounds.getSize(new THREE.Vector3());distance=Math.max(s.x,s.y,s.z)*1.8;face(currentView);document.body.dataset.focus='all'}
function select(i){if(!targets.length)return;if(selected>=0)targets[selected].mesh.material=baseMaterials.get(targets[selected].mesh);selected=(i+targets.length)%targets.length;const row=targets[selected];row.mesh.material=new THREE.MeshStandardMaterial({color:0xffcf58,roughness:.68,side:THREE.DoubleSide});selectedText.textContent=`${row.sourceElementFileId} · ${row.sourceNameEnglishExactHeader}\nFMA ${row.sourceFmaConceptId} · BP ${row.sourceRepresentationId} · ${row.lateralityFromExplicitOfficialRelation??'좌우 구분 없음'}\n${row.candidateProductRegion} · source only`;
 for(const b of list.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.id===row.sourceElementFileId));document.body.dataset.selectedSourceId=row.sourceElementFileId;focusObject(row.mesh);document.body.dataset.focus=row.candidateProductRegion;window.t72QaProof.selection={sourceElementFileId:row.sourceElementFileId,stableMeshAssetId:row.stableMeshAssetId,region:row.candidateProductRegion,highlightApplied:true,frameUnchanged:true};face(currentView)}
function load(path){return new Promise((resolve,reject)=>loader.load(path,resolve,undefined,reject))}
window.t72QaProof={loaded:false,rendererCount:1,rootName:root.name,rootCount:1,canvasCount:1,packages:[],meshNodeCount:0,targetCount:0,views:[],selection:null,consoleErrors:[],frame:'HUMAN_ATLAS_RH_M_XLEFT_YHEAD_ZANTERIOR',pose:'bodyparts3d-r4-static-reference'};
window.addEventListener('error',e=>window.t72QaProof.consoleErrors.push(String(e.message)));
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>face(b.dataset.view));document.querySelector('#fit').addEventListener('click',fitAll);
document.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();select(selected+1)}else if(e.key==='ArrowUp'){e.preventDefault();select(selected<0?targets.length-1:selected-1)}else if(e.key==='1')face('front');else if(e.key==='2')face('back');else if(e.key==='3')face('side');else if(e.key==='Escape')fitAll()});new ResizeObserver(frame).observe(document.querySelector('#stage'));window.addEventListener('resize',frame);
async function main(){const all=await Promise.all(packageSpecs.map(async spec=>({spec,gltf:await load(spec.path)})));let count=0;
 for(const {spec,gltf} of all){const ex=gltf.parser.json.extras??{};if(ex.frame!=='HUMAN_ATLAS_RH_M_XLEFT_YHEAD_ZANTERIOR'||ex.pose!=='bodyparts3d-r4-static-reference')throw Error(`${spec.id} frame/pose contract mismatch`);root.add(gltf.scene);let n=0;gltf.scene.traverse(o=>{if(!o.isMesh)return;n++;count++;let source=o.userData.sourceElementFileId?o.userData:o.parent?.userData??o.userData;let isTarget=spec.targets&&source.sourceElementFileId;if(isTarget){const material=new THREE.MeshStandardMaterial({color:0x8ac8de,roughness:.78,side:THREE.DoubleSide});o.material=material;baseMaterials.set(o,material);targets.push({...source,mesh:o})}else{o.material=new THREE.MeshStandardMaterial({color:spec.id.startsWith('T52')?0x8797a4:0xb29b87,roughness:.88,side:THREE.DoubleSide})}});window.t72QaProof.packages.push({id:spec.id,nodeCount:gltf.parser.json.nodes?.length??0,frame:ex.frame,pose:ex.pose});}
 targets.sort((a,b)=>a.sourceElementFileId.localeCompare(b.sourceElementFileId));const expected=['FJ1433','FJ1433M','FJ1446','FJ1446M','FJ1447','FJ1447M','FJ1464','FJ1464M','FJ3200','FJ3289','FJ3309'];if(targets.map(x=>x.sourceElementFileId).join(',')!==expected.join(','))throw Error('T72 GLB target IDs differ from exact frozen order');
 for(const row of targets){const b=document.createElement('button');b.type='button';b.dataset.id=row.sourceElementFileId;b.textContent=`${row.sourceNameEnglishExactHeader} · ${row.sourceElementFileId}`;b.addEventListener('click',()=>select(targets.indexOf(row)));list.append(b)}
 wholeBounds.setFromObject(root);window.t72QaProof={...window.t72QaProof,loaded:true,meshNodeCount:count,targetCount:targets.length,sceneNodeCount:root.children.length,wholeBoundsM:{min:wholeBounds.min.toArray(),max:wholeBounds.max.toArray()}};document.body.dataset.loaded='true';document.body.dataset.rendererCount='1';document.body.dataset.rootCount=String(scene.children.filter(x=>x.name==='AnatomySceneRoot').length);document.body.dataset.targetCount=String(targets.length);document.body.dataset.meshNodeCount=String(count);document.body.dataset.frame=window.t72QaProof.frame;document.body.dataset.pose=window.t72QaProof.pose;status.textContent=`${count} mesh nodes · one root/renderer · T72 targets ${targets.length} · same frame/pose · internal source QA only`;fitAll();select(0)}
main().catch(e=>{status.textContent=`QA loading failed: ${String(e)}`;console.error(e);window.t72QaProof.consoleErrors.push(String(e))});
