import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';
import runtime from '../../../../atlas-web/src/data/learnerMotionRuntime.generated.ts';
const R=process.cwd(),O='work/evidence/T66/priority-integration-2026-10-05';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')), sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const src=read('atlas-data/source-cache/datasets/za/compiled/manifest.json').instances;
const bundle=read('atlas-data/motion/motion-learning.json');const accepted=read('atlas-data/motion/t66-priority-action-acceptance.json');
const groups=[['앞정강근',/^Tibialis anterior muscle\./],['대퇴직근',/^Rectus femoris muscle\./],['대흉근',/^(?:\(Abdominal part|Clavicular head|Sternocostal head) of pectoralis major muscle\)?\./],['견갑거근',/^Levator scapulae\./],['능형근',/^Rhomboid (?:major|minor) muscle\./],['복직근',/^Rectus abdominis muscle\./],['외복사근',/^External abdominal oblique muscle\./]];
const matches=src.filter(s=>/Pectoralis major/.test(s.name));if(!matches.every(s=>groups[2][1].test(s.name)))console.log('pectoral names',matches.map(s=>s.name));
const typed=read('atlas-data/overlays/za-local-integration.json').objects;const rows=[];for(const [group,re] of groups){for(const s of src.filter(s=>re.test(s.name))){const direct=runtime.actions[s.sourceKey];const fallback=Object.entries(runtime.actions).filter(([k,opts])=>opts.some(o=>o.candidate?.asset.sourceBinding?.subjectSourceKey===s.sourceKey&&o.learningIntent==='muscle_action'));const options=direct?.length?direct:fallback.flatMap(([k,opts])=>opts.filter(o=>o.candidate?.asset.sourceBinding?.subjectSourceKey===s.sourceKey));const eligible=options.filter(o=>o.learningIntent==='muscle_action'&&o.candidate);rows.push({group,name:s.name,sourceKey:s.sourceKey,regionIds:typed.find(t=>t.sourceKey===s.sourceKey)?.regionIds??[],sourceSide:s.sourceLabelSide,options:eligible.map(o=>({label:o.label,learningIntent:o.learningIntent,assetId:o.candidate.asset.id,uri:o.candidate.asset.uri,sha256:o.candidate.asset.sha256,side:o.candidate.definition.side,actionId:o.candidate.definition.actionId,actualFileHashMatches:sha(o.candidate.asset.uri)===o.candidate.asset.sha256,explanation:o.text?.explanation??'',contextSurfaces:o.candidate.asset.sourceBinding?.members.length??null,poseControl:o.candidate.asset.poseControl})),passed:eligible.length>0});}}
const dependencies=[];for(const r of accepted.rows){const actual=sha(r.authoringPath);if(actual!==r.authoringSha256)throw Error('author hash '+r.authoringPath);if(sha(r.outcomePath)!==r.outcomeSha256)throw Error('outcome hash '+r.outcomePath);const a=read(r.authoringPath);for(const dep of a.verificationDependencies??[])dependencies.push({...dep,actualSha256:sha(dep.path),matches:sha(dep.path)===dep.sha256});}
if(dependencies.some(r=>!r.matches))throw Error('dependency mismatch');
const all=rows.flatMap(r=>r.options),uniqueAssets=[...new Set(all.map(r=>r.uri))];const result={runtimeHash:sha('atlas-web/src/data/learnerMotionRuntime.generated.ts'),sourceManifestHash:sha('atlas-data/source-cache/datasets/za/compiled/manifest.json'),groups:groups.map(([group])=>({group,availableSurfaces:rows.filter(r=>r.group===group).length,passedSurfaces:rows.filter(r=>r.group===group&&r.passed).length})),availableSourceSurfaces:rows.length,exactActionBindings:all.length,uniqueGlbUris:uniqueAssets.length,uniqueGlbHashes:new Set(all.map(r=>r.sha256)).size,rows,allAvailableSidesHaveMuscleActions:rows.every(r=>r.passed),sourceOnly:true,publicRedistribution:'held',humanReview:'not_performed'};
fs.writeFileSync(O+'/runtime-scope-audit.json',JSON.stringify(result,null,2)+'\n');fs.writeFileSync(O+'/dependency-audit.json',JSON.stringify({passed:true,referenceCount:dependencies.length,uniquePaths:new Set(dependencies.map(r=>r.path)).size,dependencies},null,2)+'\n');console.log(JSON.stringify({groups:result.groups,surfaces:rows.length,bindings:all.length,glbs:uniqueAssets.length,runtimeFields:Object.keys(runtime),optionFields:Object.keys(runtime.actions[rows[0]?.sourceKey]?.[0]??{})}));
