"""Record actual step03 acceptance without closing or rewriting historical T66 units."""
import pathlib,json,hashlib
R=pathlib.Path(__file__).resolve().parents[4];O=pathlib.Path(__file__).parent;P=str(O.relative_to(R))
load=lambda p:json.loads((R/p).read_text());digest=lambda p:hashlib.sha256((R/p).read_bytes()).hexdigest()
def save(p,v):(R/p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
preserved=[]
for path in ['atlas-data/motion/motion-learning.json','atlas-data/motion/authoring/registry.json','atlas-data/motion/motion-scenes.json','atlas-data/motion/motion-asset-sources.json','atlas-data/motion/t66-priority-action-acceptance.json']:
 before=json.loads((O/'baseline'/path).read_text());after=load(path);rows=[]
 for key,value in before.items():
  if isinstance(value,list):
   if value and isinstance(value[0],dict) and ('id' in value[0] or 'actionId' in value[0]):
    identity='id' if 'id' in value[0] else 'actionId';current={v[identity]:v for v in after[key]};assert all(current.get(v[identity])==v for v in value),(path,key)
   else:assert all(v in after[key] for v in value),(path,key)
   rows.append({'field':key,'before':len(value),'after':len(after[key]),'preexistingRowsUnchanged':True})
  else:assert after[key]==value,(path,key)
 preserved.append({'path':path,'rows':rows})
save(P+'/common-input-preservation.json',preserved)
out=load(P+'/action-outcome.json');obs=load(P+'/browser/observations.json');logs=load(P+'/browser/console-log.json');assert len(out)==12 and all(r['passed'] for r in out) and not logs
cases=['levator-left','levator-right','rhomboid-major-left','rhomboid-major-right','rhomboid-minor-left','rhomboid-minor-right','pectoral-clavicular-left','pectoral-clavicular-right','pectoral-sternocostal-left','pectoral-sternocostal-right','pectoral-abdominal-left','pectoral-abdominal-right']
for name in cases:
 end=next(x for x in reversed(obs) if x['name']==name+'-end');assert end['range']=='100' and end['canvasCount']==1 and end['motionContext']=='active'
 rest=next(x for x in reversed(obs) if x['name']==name+'-restored-complete');assert rest['range']=='0' and rest['motionContext'] is None and rest['ctaPressed']=='false'
assert all(x['viewport']==[1280,720] for x in obs)
images=[{'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':digest(str(p.relative_to(R)))} for p in sorted((O/'browser').glob('*.png'))];save(P+'/browser/capture-manifest.json',images)
validation={'status':'passed','acceptanceScope':'T66 step03 twelve exact native source parts/sides: pectoralis major clavicular/sternocostal/abdominal adduction, levator scapulae elevation, rhomboid major/minor retraction','contractRevision':'app-completion-2026-10-01','relatedRegression':{'passed':33,'failed':0,'log':P+'/verification/related-tests.log'},'productionBuild':{'passed':True,'typecheckAndFullMotionSchemaPolicy':True,'learnerDistributionAudit':True,'log':P+'/verification/build.log','chunkWarning':'App JS 6430954 bytes, gzip 682.96 KB exceeds existing 500 KB advisory; unchanged budget; no new performance benchmark or GPU/VRAM claim'},'emittedGeometry':{'sourceActions':12,'poseSamplesPerAction':65,'changedBroadPectoralSurfaces':4,'flippedFaceSamples':0,'newBoneContainment':0,'minimumChangedSurfaceAreaRatio':.2650327010669121,'originalPectoralReplaySamples':65,'oldUnchangedVerticesMaximumErrorMetres':0,'newNativeContextSurfacesPerSide':34,'correctedStationaryNeckSurfacesPerSide':2,'originalFamilyDependenciesVerified':126,'unchangedGirdleGlbsReused':4,'wholeTargetExtentApprovalsAdded':0,'humanReview':'not_performed'},'browser':{'cases':cases,'cssViewport':[1280,720],'singleCanvas':True,'loopAndReclickSmoothRest':True,'scrubRestMidEnd':True,'selectionAndLayerOffGuards':True,'dorsalScapularNerveToRhomboidAction':True,'keyboardCameraAndHistory':True,'consoleErrors':0,'consoleWarnings':0,'pngCount':len(images),'observationsPath':P+'/browser/observations.json','consolePath':P+'/browser/console-log.json','physicalDeviceValidation':False,'39010241440Claimed':False},'unresolvedProductBlockers':[],'knownVerificationLimitations':['Bounded authored educational ranges: pectoral preparation 8 degrees and girdle preparation/elevation 5 degrees, with closer teaching framing. They are not full action/ROM, physiological force/activation, measured axes or exact source attachment footprints.','Contact verification samples actual emitted keys and intermediate geometry, retains source-baseline overlaps and does not claim continuous collision freedom.','Original generic posture records/assets and other worker WIP are preserved; this step adopts corrected priority source-action paths, not an all-family anatomy/engineering approval.','Selective commit is an owned checkpoint on the current workspace. Preexisting U03-r5 authoring/assets/validator WIP remains required; a clean HEAD-only checkout is not claimed to include all those predecessor artifacts.','Reduced-motion policy/one-clock behavior reuses unchanged player checks; no OS accessibility setting or physical mobile device was exercised.']}
save(P+'/final-validation.json',validation)
unit={'executionStatus':'completed','acceptance':'passed','contractRevision':'app-completion-2026-10-01','acceptanceScope':validation['acceptanceScope'],'productReadiness':'local_supported_priority_shoulder_scapula_actions_ready','contentCompleteness':'partial','knownContentGaps':['Only representative adduction/elevation/retraction is supported. Other pectoral/scapular actions and physiological/full ROM are not animated.','Exact TA2 whole-group/part extent and human anatomy review remain separate, unapproved states.','Rectus abdominis/external oblique and final T66 integration remain subsequent authorized internal steps.','Out-of-priority jaw/face/breathing/E-index engineering remains deferred rather than a source gap or a gate for this step.'],'unresolvedProductBlockers':[],'actualMuscleSourceSurfaces':12,'completedPriorityGroupsThisUnit':3,'cumulativePriorityGroupsWithRepresentativeActions':5,'priorityGroupDenominator':7,'exactSourceActionBindings':12,'uniqueGlbAssets':6,'newDerivedGlbAssets':2,'reusedUnchangedGlbAssets':4,'contextSurfacesPerPackage':117,'sourceOnly':True,'publicRedistribution':'held','humanReview':'not_performed','evidence':[P+'/REPORT.md',P+'/final-validation.json',P+'/action-outcome.json',P+'/registration.json',P+'/dependency-audit.json',P+'/browser/observations.json'],'nextManualFile':'work/plans/t66-priority-atlas-2026-10-05/04-trunk.txt'}
save(P+'/scoped-acceptance.json',unit)
e=load('work/EXECUTION.json');before=json.loads((O/'baseline/work/EXECUTION.json').read_text());t=e['tasks']['T66'];assert t['executionStatus']=='in_progress' and t['acceptance']=='partial' and t['progress']['nextUnit']=='author-and-integrate-normal-motion-bone-and-nerve';t['progress']['priorityShoulderScapulaUnit']=unit
pa=t['progress']['productAcceptance'];g=pa['knownContentGaps'];g['primaryPlayableMuscleSourceSurfaces']=16;g['priorityVerifiedSourceActionBindings']=18;g['priorityVerifiedGlbAssets']=12;g['priorityNewDerivedAssetsThisUnit']=2;g['priorityGroupsWithRepresentativeActions']=5;g['priorityGroupsRemaining']=2
for r in out:
 g['priorityActualPlayableSources'][r['sourceKey']]=1
pa['unresolvedProductBlockers'][0]='우선7근육군 중 앞정강근·대퇴직근·대흉근(3부위)·견갑거근·대/소능형근의 양측 대표 작용을 실제 검증했다. 복직근·외복사근과 최종 통합은 다음 승인된 내부 단계에서 수행한다.';pa['evidence'].extend(unit['evidence']);t['progress']['priorityScopeAmendment2026-10-05']['nextManualPrompt']=unit['nextManualFile']
for key,value in before['tasks'].items():
 if key!='T66':assert e['tasks'][key]==value,key
save('work/EXECUTION.json',e)
print('step03 passed; parent partial; five of seven priority groups have representative bilateral source actions')
