"""Exact-source action adoption and emitted outcome inspection; no whole-group approval."""
import pathlib,sys,json,copy,hashlib,math,shutil
import numpy as np
R=pathlib.Path(__file__).resolve().parents[4];O=pathlib.Path(__file__).parent
sys.path[:0]=[str(R/'work/tools'),str(R/'work/evidence/T66/serial-completion-2026-10-02/unit-01')]
from author_source_surface_motion import source_geometry,array,rotation
from verify_glb_interpolation import read_glb,channel_data,node_positions,bounded_inside
load=lambda p:json.loads((R/p).read_text())
sha=lambda b:hashlib.sha256(b).hexdigest()
enc=lambda v:(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False)+'\n').encode()
vhash=lambda v:sha(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def save(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(enc(v));return str(p.relative_to(R))
def dep(p):return {'path':p,'sha256':sha((R/p).read_bytes())}
b=load('atlas-data/motion/motion-learning.json');reg=load('atlas-data/motion/authoring/registry.json');sc=load('atlas-data/motion/motion-scenes.json');policy=load('atlas-data/motion/motion-asset-sources.json');accept=load('atlas-data/motion/t66-priority-action-acceptance.json');src={r['sourceKey']:r for r in load('atlas-data/source-cache/datasets/za/compiled/manifest.json')['instances']};out=[];registrations=[]
assert not any(a['id'].startswith('T66-PRIORITY-S03-') for a in b['motionAssets'])
proof=save(O/'qualitative-action-evidence.json',{'url':'https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/muscle-tables/muscles-of-the-upper-limb/','accessedOn':'2026-10-05','locators':['levator scapulae row','pectoralis major row','rhomboideus major/minor rows'],'paraphraseKo':{'pectoralis':'대흉근은 팔 모음·굽힘·안쪽돌림에 관여합니다. 빗장뼈·복장뼈·갈비연골과 일부 배부분의 몸통 쪽 연결에서 위팔뼈 쪽으로 이어집니다. 이번 대표 시범은 팔 모음입니다.','levator':'견갑거근은 첫째–넷째 목뼈 가로돌기에서 어깨뼈 위쪽 안쪽모서리로 이어지며 어깨뼈 올림에 관여합니다.','rhomboids':'대능형근은 둘째–다섯째 등뼈 가시돌기에서, 소능형근은 아래 목덜미인대와 일곱째 목뼈–첫째 등뼈 부근에서 어깨뼈 안쪽모서리로 이어집니다. 어깨뼈 뒤당김·올림·아래돌림에 관여하며 이번 시범은 뒤당김입니다.'},'scope':'qualitative attachment/action; authored educational masks/angles are not measured footprints, normal ROM, forces or activation','existingAttachmentEvidence':'atlas-data/terminology/muscle-attachment-content-2026-10-02.json'})
for side in ['left','right']:
 for kind,stem in [('PECT','shoulder-abduction'),('LEV','shoulder-girdle-elevation'),('RHOM','shoulder-girdle-protraction')]:
  oldfid=stem+'-'+side;oldpath=next(r['path'] for r in reversed(reg['records']) if load(r['path']).get('sourceFamilyId')==oldfid);oldar=load(oldpath);oldasset=next(a for a in b['motionAssets'] if a.get('sourceBinding',{}).get('sourceFamilyId')==oldfid);asset=copy.deepcopy(oldasset);definition=copy.deepcopy(next(d for d in b['motionDefinitions'] if d['id']==asset['motionDefinitionId']));scene=copy.deepcopy(next(s for s in sc['sceneManifests'] if s['id']==asset['staticBinding']['sceneId']));ip=next(d['path'] for d in oldar['verificationDependencies'] if d['path'].endswith('/input.json'));payload=load(ip);geo=load(oldar['geometryRecordPath']);poseqc=load(oldar['glbPoseQcPath']);contact=load(oldar['contactQcPath']);ident='T66-PRIORITY-S03-'+side[0].upper()+'-'+kind;fid='priority-'+kind.lower()+'-'+side;dest=O/(kind.lower()+'-contract-'+side)
  if kind=='PECT':
   pdir=O/('pectoral-'+side);new=load(str((pdir/'registration-input.json').relative_to(R)));members=copy.deepcopy(new['members']);entries=new['sourceSpecificEntries'];uri=f'atlas-data/assets/motion/{ident.lower()}/motion.glb';refuri=f'atlas-data/assets/derived-glb/{ident.lower()}/reference.glb'
   for target,filename in [(uri,'motion.glb'),(refuri,'reference.glb')]:path=R/target;path.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(pdir/filename,path)
   scene.update(id=ident+'-REFERENCE',assetUri=refuri,sourceAssetSha256=new['restSha256']);sc['sceneManifests'].append(scene);asset['staticBinding'].update(sceneId=scene['id'],sourceAssetSha256=new['restSha256']);definition['staticReference'].update(sceneId=scene['id'],sourceAssetSha256=new['restSha256']);asset.update(uri=uri,sha256=new['motionSha256']);asset['sourceBinding']['members']=members;geo.update(members=members,motionSha256=new['motionSha256'],restSha256=new['restSha256']);geo['family']['samples']=16;poseqc['testedKeys']=17;poseqc['motionSha256']=asset['sha256']
   # Inspect only new adjacent contact pairs; all original poses are replayed unchanged.
   raw,doc,buf=read_glb(R/uri);tracks=channel_data(doc,buf);nodes={n['extras']['sourceKey']:i for i,n in enumerate(doc['nodes'])};newbones=[e['sourceKey'] for e in new['newEntries'] if e['role']=='fixed_structure'];extra=[]
   for m in members:
    if m['role'] not in ['moving_structure','co_moving_context','deforming_passive_surface']:continue
    k=m['sourceKey'];w=node_positions(doc,buf,tracks,nodes[k],0)
    for bone in newbones:
     bw=node_positions(doc,buf,tracks,nodes[bone],0)
     if any(w.max(0)[j]<bw.min(0)[j]-.025 or w.min(0)[j]>bw.max(0)[j]+.025 for j in range(3)):continue
     prim=doc['meshes'][doc['nodes'][nodes[bone]]['mesh']]['primitives'][0];bt=array(doc,buf,prim['indices']).reshape(-1,3);baseline=bounded_inside(w,bw,bt);maximum=max(int((bounded_inside(node_positions(doc,buf,tracks,nodes[k],float(t)),bw,bt)&~baseline).sum()) for t in np.linspace(0,asset['clip']['durationSeconds'],65));extra.append({'sourceKey':k,'boneSourceKey':bone,'newContainmentMaximum':maximum})
   save(dest/'appended-contact.json',extra);assert all(r['newContainmentMaximum']==0 for r in extra),[(src[r['sourceKey']]['name'],src[r['boneSourceKey']]['name'],r['newContainmentMaximum']) for r in extra if r['newContainmentMaximum']]
   contact['appendedNativeBoneContactChecks']=extra;contact['reuseReceiptPath']=str((pdir/'reuse-receipt.json').relative_to(R));qcs={}
   # Original morphs/bones and their original nearby contacts are exactly unchanged.
   for key,path in oldar['glbInterpolationQcPaths'].items():
    qc=load(path);qc['motionGlbSha256']=asset['sha256'];qc['dependencyReuseReceipt']=contact['reuseReceiptPath'];qcs[key]=save(dest/('interpolation-'+key+'.json'),qc)
   qcs.update(new['interpolationPaths'])
   for m in members:
    key=m['sourceKey']
    if key in new['newDeformers']:
     qc=load(qcs[key]);metric=next(r for r in geo['surfaceMetrics'] if r['sourceKey']==key);metric.update(role=m['role'],flips=0,minimumAreaRatio=qc['geometry']['minimumAreaRatio']);row=next(r for r in poseqc['rows'] if r['sourceKey']==key);row.clear();row.update(sourceKey=key,sourceFrameComparison='authored_surface_deformation',requiresGeometryQc=True,passed=True)
    elif key in [e['sourceKey'] for e in new['newEntries']]+new['correctedStationaryContext']:
     w=source_geometry(src[key],'overview')[-1];error=max(float(np.linalg.norm(node_positions(doc,buf,tracks,nodes[key],float(t))-w,axis=1).max()) for t in np.linspace(0,asset['clip']['durationSeconds'],65));assert error<1e-6;metric={'sourceKey':key,'role':m['role'],'flips':0,'minimumAreaRatio':1,'maximumDisplacementMetres':0};row={'sourceKey':key,'sourceFrameComparison':'exact_rigid_source_frame','passed':True,'maximumWorldErrorMetres':error,'requiresGeometryQc':False}
     if key in new['correctedStationaryContext']:
      gm=next(r for r in geo['surfaceMetrics'] if r['sourceKey']==key);gm.clear();gm.update(metric);qr=next(r for r in poseqc['rows'] if r['sourceKey']==key);qr.clear();qr.update(row)
     else:geo['surfaceMetrics'].append(metric);poseqc['rows'].append(row)
   for row in poseqc['rows']:
    if row['sourceKey'] in qcs:row.update(geometryQcPath=qcs[row['sourceKey']],geometryQcSha256=sha((R/qcs[row['sourceKey']]).read_bytes()))
   receipts=[contact['reuseReceiptPath'],str((pdir/'authored-contact-input.json').relative_to(R))]
  else:
   uri=asset['uri'];members=copy.deepcopy(asset['sourceBinding']['members']);entries=payload['members'];qcs=oldar['glbInterpolationQcPaths'];receipts=[save(dest/'reuse-receipt.json',{'originalAuthoringPath':oldpath,'originalAuthoringSha256':sha((R/oldpath).read_bytes()),'unchangedMotionGlbSha256':asset['sha256'],'unchangedReferenceGlbSha256':oldar['restSha256'],'changes':'Exact-source action review, reverse preparation/action where required, new selectors; actual tracks/QC/source geometry unchanged','oldPassiveSelectorsPreserved':True})]
  raw,doc,buf=read_glb(R/uri);assert sha(raw)==asset['sha256'];tracks=channel_data(doc,buf);nodes={n['extras']['sourceKey']:i for i,n in enumerate(doc['nodes'])};duration=asset['clip']['durationSeconds'];targets=[m['sourceKey'] for m in members if ('pectoralis major' in src[m['sourceKey']]['name'] if kind=='PECT' else 'Levator scapulae' in src[m['sourceKey']]['name'] if kind=='LEV' else 'Rhomboid' in src[m['sourceKey']]['name'])];assert len(targets)=={'PECT':3,'LEV':1,'RHOM':2}[kind]
  direction='forward' if kind=='LEV' else 'reverse'
  for key in targets:
   entry=next(e for e in entries if e['sourceKey']==key);fixed=entry['fixedVertexIndices'];moving=entry['movingVertexIndices'];poses=[node_positions(doc,buf,tracks,nodes[key],float(t)) for t in np.linspace(0,duration,65)];span=lambda w:float(np.linalg.norm(w[fixed].mean(0)-w[moving].mean(0)));spans=[span(w) for w in poses];shortening=(spans[0]-spans[-1]) if direction=='forward' else spans[-1]-spans[0];err=max(float(np.linalg.norm(w[fixed]-poses[0][fixed],axis=1).max()) for w in poses);assert shortening>.0005 and err<1e-6,(src[key]['name'],shortening,err)
   assert all((a-b if direction=='forward' else b-a)>-1e-7 for a,b in zip(spans,spans[1:])),(key,spans)
   scap=next(k for k in nodes if src[k]['name']=='Scapula.'+side[0]);ds=node_positions(doc,buf,tracks,nodes[scap],duration).mean(0)-node_positions(doc,buf,tracks,nodes[scap],0).mean(0)
   if kind=='LEV':assert ds[1]>.005
   if kind=='RHOM':assert (ds[0] if side=='left' else -ds[0])>.001 and ds[2]>.001
   postfix='CLAV' if 'Clavicular' in src[key]['name'] else 'STERN' if 'Sternocostal' in src[key]['name'] else 'ABDOM' if kind=='PECT' else 'MAJOR' if 'major' in src[key]['name'] else 'MINOR' if 'minor' in src[key]['name'] else 'LEV'
   aid=ident+'-'+postfix+'-ASSET';out.append({'sourceKey':key,'side':side,'kind':kind,'assetId':aid,'motionSha256':asset['sha256'],'passed':True,'actionDirection':direction,'shorteningMetres':shortening,'fixedMaskErrorMetres':err,'surfaceExcursionMetres':max(float(np.linalg.norm(w-poses[0],axis=1).max()) for w in poses),'scapulaPreparationDisplacementMetres':ds.tolist(),'geometryQcPath':qcs[key],'contextSurfaceCount':len(members),'inspectedPoseSamples':65,'physiologicalContractionClaimed':False,'measuredAttachmentFootprints':False})
  geo['family']['id']=fid;poseqc['familyId']=fid
  for m in members+geo['members']+geo['surfaceMetrics']:
   if m['sourceKey'] in targets:m['role']='deforming_muscle_surface'
  label={'PECT':'팔 모음 · 어깨 모음','LEV':'어깨뼈 올림','RHOM':'어깨뼈 뒤당김'}[kind];explanation={'PECT':'팔을 살짝 벌린 준비 자세에서 몸통 쪽으로 모으는 대흉근의 대표 작용을 봅니다. 쇄골부·흉늑부·배부분의 몸통 쪽 연결은 유지되고 위팔뼈 쪽을 따라 표면이 변형됩니다. 선택한 부분과 주변 구조를 함께 표시합니다.','LEV':'목뼈 쪽 연결을 유지하면서 어깨뼈가 위로 올라가는 견갑거근의 대표 작용을 봅니다. 어깨뼈·빗장뼈와 연결된 팔의 문맥을 함께 관찰합니다.','RHOM':'어깨뼈가 앞쪽으로 이동한 준비 자세에서 척추 쪽으로 뒤당겨지는 능형근의 대표 작용을 봅니다. 대능형근과 소능형근은 각각의 실제 표면과 척추 쪽 연결을 유지합니다.'}[kind];posture='교육용으로 작성한 짧은 대표 움직임입니다. 준비 구간과 선택 근육의 작용 구간을 구분하며 정상 가동범위나 힘을 계산하지 않습니다.';context='주변 근육과 뼈는 온전한 표면을 유지하며 함께 움직이거나 수동으로 변형됩니다. 개별 근육의 힘·활성도를 뜻하지 않습니다.'
  author=copy.deepcopy(oldar);author.update(id=ident+'-AUTHORING',sourceFamilyId=fid,supportedSubjectKeys=targets,motorRoleSourceKeys=targets,anatomicalMotorRoleClaimed=True,scope='exact_source_parts_bilateral_educational_action',motionSha256=asset['sha256'],restSha256=geo['restSha256'],geometryRecordPath=save(dest/'geometry-record.json',geo),glbPoseQcPath=save(dest/'glb-pose-qc.json',poseqc),contactQcPath=save(dest/'contact-qc.json',contact),glbInterpolationQcPaths=qcs,actionOutcomePath=str((O/'action-outcome.json').relative_to(R)),qualitativeActionEvidencePath=proof)
  author['poseRange']['actionDirection']=direction
  author['claims']=[{'id':ident+'-'+f,'field':f,'appliesTo':scope,'contextId':cid,'value':value} for f,scope,cid,value in [('action','action_explanation',None,explanation),('model_posture','posture_condition',None,posture),('model_context','context_role',ident+'-CONTEXT',context)]]
  for field,roles in [('movingBoneKeys',['moving_structure']),('fixedBoneKeys',['fixed_structure']),('coMovingContextKeys',['co_moving_context']),('passiveDeformationKeys',['deforming_passive_surface'])]:author[field]=[m['sourceKey'] for m in members if m['role'] in roles]
  save(dest/'authoring-pending.json',author)
  for key in targets:
   outcome=next(r for r in out if r['sourceKey']==key);idbase=outcome['assetId'][:-6];act={'id':idbase+'-ACTION','subjectKind':'muscle','subjectIds':[],'sourceSubjectKeys':[key],'sideApplicability':side,'jointBindingState':'source_family_bound','sourceFamilyId':fid,'jointBindingNote':'Exact source action with emitted direction and attachment-context inspection; canonical/group extent not approved','targetJointIds':[],'actionLabel':label,'explanation':explanation,'postureConditions':[posture],'stabilizationConditions':[],'stabilizationNote':context,'contextRoles':[{'contextId':ident+'-CONTEXT','role':'unspecified','contractionRole':'unspecified','explanation':context}],'sourceRefs':[{'layer':'source_family_record','field':c['field'],'appliesTo':c['appliesTo'],'contextId':c['contextId'],'claimId':c['id'],'valueHash':vhash(c['value']),'evidenceId':author['id'],'fieldEvidenceId':None} for c in author['claims']],'legacyJointActionId':None};d=copy.deepcopy(definition);a=copy.deepcopy(asset);d.update(id=idbase+'-MOTION',actionId=act['id'],instanceId=key,side=side,sourceFamilyId=fid,movingStructureIds=author['movingBoneKeys'],fixedStructureIds=author['fixedBoneKeys']);d['poseSourceRefs']=[{'layer':'authoring_record','field':'motion_pose_range','appliesTo':'motion_pose_range','contextId':None,'claimId':author['id'],'valueHash':vhash(author['poseRange']),'evidenceId':author['id'],'fieldEvidenceId':None}];a.update(id=outcome['assetId'],motionDefinitionId=d['id'],revision='t66-priority-shoulder-scapula-r1');a['sourceBinding'].update(subjectKind='muscle',subjectSourceKey=key,sourceFamilyId=fid,members=members);a['poseControl']={'label':'준비 자세 각도' if direction=='reverse' else '어깨띠 올림 각도','startDegrees':0,'endDegrees':author['poseRange']['endDegrees'],'combination':'single_dof_only','actionDirection':direction,'observationDirection':[.55,0,.84] if kind=='PECT' else [.35,.1,-.93]}
   names=['pectoralis major','Scapula.','Clavicle.','Humerus.','sternum','rib.'] if kind=='PECT' else ['Scapula.','Clavicle.','Levator scapulae','Rhomboid','Vertebra C','Vertebra T1','Vertebra T2','Vertebra T3','Vertebra T4','Vertebra T5']
   a['poseControl']['framingSourceKeys']=[m['sourceKey'] for m in members if any(n.lower() in src[m['sourceKey']]['name'].lower() for n in names)]
   if kind!='PECT':a['poseControl']['contextOpacity']=.25
   b['muscleActions'].insert(0,act);b['motionDefinitions'].append(d);b['motionAssets'].append(a);policy['productionMotionAssetIds'].append(a['id']);registrations.append({'sourceKey':key,'side':side,'assetId':a['id'],'actionId':act['id'],'familyId':fid,'uri':uri,'newGlb':kind=='PECT','authoringPending':str((dest/'authoring-pending.json').relative_to(R))})
op=save(O/'action-outcome.json',out)
for pending in sorted(set(r['authoringPending'] for r in registrations)):
 author=load(pending);matching=[r for r in registrations if r['authoringPending']==pending];uri=matching[0]['uri'];paths=[d['path'] for d in author['verificationDependencies'] if (R/d['path']).exists()]+[uri,author['geometryRecordPath'],author['glbPoseQcPath'],author['contactQcPath'],*author['glbInterpolationQcPaths'].values(),proof,op];author['verificationDependencies']=[dep(p) for p in dict.fromkeys(paths)];ap=save(R/f"atlas-data/motion/authoring/{author['id'].lower()}.json",author);reg['records'].append({'id':author['id'],'path':ap,'sha256':sha((R/ap).read_bytes())})
 for r in matching:accept['rows'].append({'actionId':r['actionId'],'assetId':r['assetId'],'sourceKey':r['sourceKey'],'side':r['side'],'motionSha256':author['motionSha256'],'authoringPath':ap,'authoringSha256':sha((R/ap).read_bytes()),'outcomePath':op,'outcomeSha256':sha((R/op).read_bytes())});r['authoringPath']=ap
for path,v in [('atlas-data/motion/motion-learning.json',b),('atlas-data/motion/motion-scenes.json',sc),('atlas-data/motion/authoring/registry.json',reg),('atlas-data/motion/motion-asset-sources.json',policy),('atlas-data/motion/t66-priority-action-acceptance.json',accept)]:save(R/path,v)
save(O/'registration.json',registrations);print('registered',len(out),'exact source actions; 2 new GLBs and 4 unchanged GLBs',flush=True)
